string1 = "CAMBRIDGE"
print("The string is: " + string1)
print("ALL THE CHARACTER WHICH ARE BEING DISPLAYING IS IN THE REVERSE ORDER")
# print("First character: " + string1[-1])
# print("Second character: " + string1[-2])
# print("Third character: " + string1[-3])
# print("Fourth character: " + string1[-4])
# print("Fifth character: " + string1[-5])
# print("Sixth character: " + string1[-6])
# print("Seventh character: " + string1[-7])
# print("Eight character: " + string1[-8])
# print("Ninth character: " + string1[-9])
# print("Tenth character: " + string1[-10])

try:
    print("First character: " + string1[-1])
    print("Second character: " + string1[-2])
    print("Third character: " + string1[-3])
    print("Fourth character: " + string1[-4])
    print("Fifth character: " + string1[-5])
    print("Sixth character: " + string1[-6])
    print("Seventh character: " + string1[-7])
    print("Eight character: " + string1[-8])
    print("Ninth character: " + string1[-9])
    print("Tenth character: " + string1[-10])
except IndexError:
    print("Invalid Index")